[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "pharmvar_api"
version = "0.1.0"
description = "Python wrapper for the PharmVar API"
requires-python = ">=3.12"
keywords = ["PharmVar", "pharmacogenomics", "api wrapper", "pharmvar_api"]
authors = [
    {name = "Sven van der Maas", email = "svenvdm2013@gmail.com"}
]
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E.*"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3.12"
]

[project.urls]
Repository = "https://github.com/Svenvdm/pharmvar_api"
